### ISSUE TITLE
AtTabs内嵌AtModal或自定义position: fixed的view显示问题

### ISSUE THREAD

**Issue by WilsonLau0755** [jd-opensource/taro-ui#828]
**问题描述**
微信小程序项目中使用AtTabs，采用垂直方向的tabs布局。在AtTabsPane中内嵌了一个AtModal（或自定义的modal，position: fixed），modal及自定义modal样式均为基于pane容器内的定位，而非基于整个窗口。

**复现步骤**
1、AtTabs采用vertical，通过循环生成AtTabsPane
2、AtTabsPane内部嵌套AtModal
3、微信开发者工具中效果显示modal相对于AtTabsPane定位而非整个界面
（图片上传几次都失败了。）

**期望行为**
modal或position：fixed的自定义modal是基于整个窗口的布局

**报错信息**
无报错

**系统信息**
- Taro版本：v1.3.19
- Taro UI 版本 2.2.2
- 报错平台 weapp

**补充信息**

**Comment by fanlion** [comment]
@WilsonLau0755 

文档中提到：请勿在 AtTab 组件内嵌套 position:fixed 布局的组件，比如：curtain,message,toast,action-sheet,modal,float-layout,drawer,picker。

没有给出解释原因，该限制导致AtTab使用场景十分有限

**Comment by damaohub** [comment]
> @WilsonLau0755
> 
> 文档中提到：请勿在 AtTab 组件内嵌套 position:fixed 布局的组件，比如：curtain,message,toast,action-sheet,modal,float-layout,drawer,picker。
> 
> 没有给出解释原因，该限制导致AtTab使用场景十分有限

有没有解决办法，这个太糟糕了

**Comment by cncolder** [comment]
@damaohub 如果是水平 Tabs. 参考:

```css
.at-tabs {
    min-height: 100vh;
}
.at-modal {
    min-height: 100vh;
    transform: translateY(-88px);
}
```

垂直 Tabs 道理类似. 只是不清楚 TabHeader 宽度是不是固定的.
